version: '3.9'

services:
  php:
    build: ./docker-images/php-apache
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/html
      
  mysql:
    image: mysql:5.7
    hostname: monitoring-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=monitoring
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8888:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - UPLOAD_MAX_FILESIZE=20M
      - POST_MAX_SIZE=20M
      - UPLOAD_LIMIT=300M
      - PHP_UPLOAD_MAX_FILESIZE=300M
      - PHP_POST_MAX_SIZE=300M
    depends_on:
      - mysql
